# deploy
name: CICD using maven and SL lab 
on: 
 push: 
   branches: ["master"]
 workflow_dispatch: 
jobs: 
  buildandDeploy:
    runs-on: ubuntu-latest
    steps: 
    - name: Clone the Repo 
      uses: actions/checkout@v4 
    - name: Setup JDK 11 and maven 
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'
    - name: Build with Maven 
      run: mvn -B package --file pom.xml 
    - name: connect to LAb and deploy code on tomcat9
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      with:
       host: 'vishnuraj2110gmsl0045.simplilearnlabs.com'
       user: 'vishnuraj2110gm'
       pass: '2110gm0A@7pjch'
       port: 42006
       connect_timeout: 10s
       first_ssh: |
          sudo chmod 777 /var/lib/tomcat9/webapps
       scp: |
          './target/*war' => /var/lib/tomcat9/webapps
       last_ssh: |
          sudo systemctl restart tomcat9

    - name: Checkout code
      uses: action/https://github.com/vishnuraj2110/MavenBuild-SL-githubActions.git@master

    - name: Trigger Jenkins Job
      env:
        JENKINS_USER: 'admin'
        JENKINS_API_TOKEN: '1153e83d86a96e872cee3dfa69e4d895f7'
        JENKINS_JOB_URL: 'http://16.171.0.253:8080'
      run: |
        curl -X POST "${JENKINS_JOB_URL}/buildWithParameters" \
        --user "${JENKINS_USER}:${JENKINS_API_TOKEN}" \
        --data-urlencode "token=${{ secrets.JENKINS_API_TOKEN }}"

